(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("HoudiniMASH_AUI_CordovaLib",""):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
(function(h){var f=window.AmazonUIPageJS||window.P,k=f._namespace||f.attributeErrors,b=k?k("MASHCorePluginJS",""):f;b.guardFatal?b.guardFatal(h)(b,window):b.execute(function(){h(b,window)})})(function(h,f,k){h.register("mash-interface-combiner",function(){return function(){for(var b={},d=0;d<arguments.length;d++){var c=arguments[d],a;for(a in c)c.hasOwnProperty(a)&&(b[a]=c[a])}return b}});"use strict";h.register("mash-amazon",function(){f.amazon=f.amazon||{};f.app=f.app||{};"willReappear"in f.app||
(f.app.willReappear=function(){});return f.amazon});h.register("mash-core-interface-factory",function(){return function(b,d,c){return{navigate:function(a){try{a=a||{},a.transitionEffect=a.transitionEffect||"slide",b.validateFunctions(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("navigate",a),d.navigate(a)}catch(e){c.handleError(e,"navigate",a.failCallback)}},goBack:function(a){try{a=a||{},b.validateFunctions(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("goBack",
a),d.goBack(a)}catch(e){c.handleError(e,"goBack",a.failCallback)}},launchIntentURL:function(a){try{a=a||{},b.validateParameters1_3(a,["url"]),b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("launchIntentURL",a),d.launchIntentURL(a)}catch(e){c.handleError(e,"launchIntentURL",a.failCallback)}},canLaunchIntentURL:function(a){try{a=a||{},b.validateParameters1_3(a,["url"]),b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("canLaunchIntentURL",
a),d.canLaunchIntentURL(a)}catch(e){c.handleError(e,"canLaunchIntentURL",a.failCallback)}},openInExternalBrowser:function(a){try{a=a||{},b.validateParameters(a,["url"]),b.validateFunctions(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("openInExternalBrowser",a),d.openInExternalBrowser(a)}catch(e){c.handleError(e,"openInExternalBrowser",a.failCallback)}},share:function(a){try{a=a||{},b.validateParameters(a,["messagePlain","messagePlain160","messagePlain140","messageHTML","subject"]),
b.validateFunctions(a,["successCallback","failCallback","shareServiceSelectedCallback"]),a=c.wrapSuccessAndFailCallbacks("share",a),d.share(a)}catch(e){c.handleError(e,"share",a.failCallback)}}}}});h.when("mash-util","mash-core-impl","mash-error-util","mash-core-interface-factory").register("mash-core-interface",function(b,d,c,a){return a(b,d,c)});h.when("mash-error").register("mash-util",function(b){function d(){}d.prototype={buttonNamesToIds:{navButtonLeft:0,navButtonRight:1},validateParameters:function(b,
a){for(var e=0;e<a.length;++e){var g=a[e];if(b[g]===k||null===b[g])throw"Invalid or missing parameter: "+g;}},validateParameters1_3:function(c,a){try{this.validateParameters(c,a)}catch(e){throw new b.Error(b.Error.INVALID_ARGUMENTS);}},validateFunctions:function(b,a){for(var e=0;e<a.length;++e){var g=a[e];if(b[g]!==k&&null!==b[g]&&"function"!==typeof b[g])throw"Invalid function value for parameter: "+g;}},validateFunctions1_3:function(c,a){try{this.validateFunctions(c,a)}catch(e){throw new b.Error(b.Error.INVALID_ARGUMENTS);
}},validateBool:function(b,a){b===k&&(b=a);0===b?b=!1:1===b&&(b=!0);if(!0!==b&&!1!==b)throw"Type mismatch";return b},validateBool1_3:function(c,a){try{return this.validateBool(c,a)}catch(e){throw new b.Error(b.Error.INVALID_ARGUMENTS);}}};return new d});h.register("mash-error",function(){var b=function(a){this.code=a};b.PERMISSION_DENIED=1001;b.TIMEOUT=1002;b.NOT_SUPPORTED=1003;b.OUT_OF_MEM=1004;b.UNKNOWN=1005;b.USER_CANCELLED=1006;b.USER_CANCELED=b.USER_CANCELLED;b.INVALID_ARGUMENTS=1007;b.OPERATION_IN_PROGRESS=
1008;var d=function(a){this.code=a};d.INTENT_NOT_FOUND=1;var c=function(a){this.code=a};c.CANNOT_OPEN_CAMERA=1;var a=function(a){this.code=a};a.CANNOT_OPEN_CAMERA=1;a.INVALID_CARD_TYPE=2;a.NO_SUPPORTED_CARD_TYPES=3;var e=function(a){this.code=a};e.NOT_LOGGED_IN=1;var g=function(a){this.code=a};g.NO_VIDEO_PLAYER_FOUND=1;var l=function(a){this.code=a};l.CANNOT_OPEN_CAPTURE_MECHANISM=1;l.FILE_SIZE_EXCEEDED=2;l.FILE_NOT_FOUND=3;l.MIME_TYPE_NOT_SUPPORTED=4;return{Error:b,LaunchIntentURLError:d,BarcodeScanError:c,
CardScannerError:a,LogoutError:e,VideoError:g,OpenFileChooserError:l}});h.when("mash-error").register("mash-error-util",function(b){function d(a){for(var g in b)if(b.hasOwnProperty(g)&&!a(g,b[g]))break}function c(a){a=a||{};var g,c=a.error_type;c&&c in b&&(c=b[c],"string"===typeof a.code&&a.code in c&&(g=new c(c[a.code])));!g&&"object"===typeof a&&a&&d(function(b,c){"string"===typeof a.code&&a.code in c?g=new c(c[a.code]):a.constructor===c&&a.code&&(g=a);return!g});return g||new b.Error(b.Error.UNKNOWN)}
function a(a,b){b=b||{};var c=b.successCallback,d=b.failCallback;b.successCallback=function(){"function"===typeof c&&c.apply(this,arguments)};b.failCallback=function(a){"function"===typeof d&&d.apply(this,arguments)};b.successCallback.monitorWrapper=b.failCallback.monitorWrapper=!0;return b}return{forEachErrorType:d,resolveError:c,errorName:function(a){a=c(a);var b;d(function(c,d){if(a.constructor!==d)return!0;for(var f in d)d.hasOwnProperty(f)&&d[f]===a.code&&(b=[c,f].join("."));return!b});return b||
"Error.UNKNOWN"},handleError:function(b,d,f){console.error("Error during MASH call: "+(JSON.stringify(b)||b.toString()));var h={failCallback:f};"function"===typeof f&&f.monitorWrapper||(h=a(d,h));h.failCallback.apply(h.failCallback,[c(b)])},wrapSuccessAndFailCallbacks:a}});"use strict";h.register("mash-registration-error-handler",function(){return function(b){f&&f.ueLogError&&f.ueLogError(b,{attribution:"[PRIMENOW_MASH]",logLevel:"ERROR"})}})});
/* ******** */
(function(d){var b=window.AmazonUIPageJS||window.P,e=b._namespace||b.attributeErrors,c=e?e("MASHSignInOutPluginJS",""):b;c.guardFatal?c.guardFatal(d)(c,window):c.execute(function(){d(c,window)})})(function(d,b,e){d.when("mash-util","mash-signinout-impl","mash-error-util").register("mash-signinout-interface",function(c,d,b){return{showLoginDialog:function(a){try{a=a||{},c.validateFunctions(a,["successCallback","failCallback"]),a=b.wrapSuccessAndFailCallbacks("showLoginDialog",a),d.showLoginDialog(a)}catch(e){b.handleError(e,
"showLoginDialog",a.failCallback)}},logout:function(a){try{a=a||{},c.validateFunctions1_3(a,["successCallback","failCallback"]),a=b.wrapSuccessAndFailCallbacks("logout",a),d.logout(a)}catch(e){b.handleError(e,"logout",a.failCallback)}}}})});
/* ******** */
(function(f){var h=window.AmazonUIPageJS||window.P,g=h._namespace||h.attributeErrors,b=g?g("HoudiniMASHPluginJS",""):h;b.guardFatal?b.guardFatal(f)(b,window):b.execute(function(){f(b,window)})})(function(f,h,g){f.when("mash-util","mash-houdini-impl","mash-error-util").register("mash-houdini-base",function(b,e,c){return{launchAppStoreListing:function(a){try{a=a||{},a=c.wrapSuccessAndFailCallbacks("houdini.launchAppStoreListing",a),e.launchAppStoreListing(a)}catch(b){c.handleError(b,"houdini.launchAppStoreListing",
a.failCallback)}},displayModal:function(a){try{a=a||{},a=c.wrapSuccessAndFailCallbacks("houdini.displayModal",a),e.displayModal(a)}catch(b){c.handleError(b,"houdini.displayModal",a.failCallback)}},displayBottomSheet:function(a){try{a=a||{},a=c.wrapSuccessAndFailCallbacks("houdini.displayBottomSheet",a),b.validateParameters1_3(a,["template","templateArgs"]),b.validateFunctions1_3(a,["successCallback"]),e.displayBottomSheet(a)}catch(d){c.handleError(d,"houdini.displayBottomSheet",a.failCallback)}},
requestPushNotificationPermissions:function(a){try{a=a||{},b.validateParameters1_3(a,["iosMessage","androidMessage","title"]),b.validateFunctions1_3(a,["successCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.requestPushNotificationPermissions",a),e.requestPushNotificationPermissions(a)}catch(d){c.handleError(d,"houdini.requestPushNotificationPermissions",a.failCallback)}}}});"use strict";f.when("mash-util","mash-houdini-impl","mash-error-util").register("mash-houdini-cart",function(b,e,c){return{cart:{addItem:function(a){try{a=
a||{},b.validateParameters1_3(a,["asin","offerId"]),b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.cart.addItem",a),e.cart.addItem(a)}catch(d){c.handleError(d,"houdini.cart.addItem",a.failCallback)}},updateItem:function(a){try{a=a||{},b.validateParameters1_3(a,["asin","offerId","quantity"]),b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.cart.updateItem",a),e.cart.updateItem(a)}catch(d){c.handleError(d,
"houdini.cart.updateItem",a.failCallback)}}}}});"use strict";f.when("mash-util","mash-houdini-impl","mash-error-util").register("mash-houdini-deliverymap",function(b,e,c){return{deliveryMap:{updateLocations:function(a){try{a=a||{},a.destination!==g&&null!==a.destination&&b.validateParameters1_3(a.destination,["latitude","longitude"]),a.courier!==g&&null!==a.courier&&b.validateParameters1_3(a.courier,["latitude","longitude"]),a.origin!==g&&null!==a.origin&&b.validateParameters1_3(a.origin,["latitude",
"longitude"]),a.orderType=a.orderType||"DELIVERY",b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.deliveryMap.updateLocations",a),e.deliveryMap.updateLocations(a)}catch(d){c.handleError(d,"houdini.deliveryMap.updateLocations",a.failCallback)}},updateControlAreaHeight:function(a){a={height:a};try{b.validateParameters1_3(a,["height"]),a=c.wrapSuccessAndFailCallbacks("houdini.deliveryMap.updateControlAreaHeight",a),e.deliveryMap.updateControlAreaHeight(a)}catch(d){throw c.handleError(d,
"houdini.deliveryMap.updateControlAreaHeight",a.failCallback),d;}},updateMapBarItems:function(a){try{a=a||{},b.validateParameters1_3(a,["left","right"]),b.validateParameters1_3(a.left,["text","color"]),b.validateParameters1_3(a.right,["text","color"]),a=c.wrapSuccessAndFailCallbacks("houdini.deliveryMap.updateMapBarItems",a),e.deliveryMap.updateMapBarItems(a)}catch(d){c.handleError(d,"houdini.deliveryMap.updateMapBarItems",a.failCallback)}},init:function(a){try{a=a||{},b.validateParameters1_3(a,["appId",
"appCode"]),a=c.wrapSuccessAndFailCallbacks("houdini.deliveryMap.init",a),e.deliveryMap.init(a)}catch(d){c.handleError(d,"houdini.deliveryMap.init",a.failCallback)}}}}});"use strict";f.when("mash-util","mash-houdini-impl","mash-error-util").register("mash-houdini-goto",function(b,e,c){return{goto:{search:function(a){try{a=a||{},a=c.wrapSuccessAndFailCallbacks("houdini.goto.search",a),e.goto.search(a)}catch(b){c.handleError(b,"houdini.goto.search",a.failCallback)}},voiceSearch:function(a){try{a=a||
{},a=c.wrapSuccessAndFailCallbacks("houdini.goto.voiceSearch",a),e.goto.voiceSearch(a)}catch(b){c.handleError(b,"houdini.goto.voiceSearch",a.failCallback)}}}}});"use strict";f.when("mash-interface-combiner","mash-houdini-base","mash-houdini-cart","mash-houdini-deliverymap","mash-houdini-goto","mash-houdini-marketplace","mash-houdini-transition","mash-houdini-pickuptracking","mash-houdini-pfenotifications").register("mash-houdini-interface",function(){var b=Array.prototype.slice.call(arguments),e=
b.shift();return{houdini:e.apply(e,b)}});"use strict";f.when("mash-util","mash-houdini-impl","mash-error-util").register("mash-houdini-marketplace",function(b,e,c){return{marketplace:{updateLocation:function(a){try{a=a||{},b.validateParameters1_3(a,["marketplaceId","domain","mapStartLocation","menuBackgroundURL","postalCode"]),b.validateParameters1_3(a.mapStartLocation,["latitude","longitude"]),b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.marketplace.updateLocation",
a),e.marketplace.updateLocation(a)}catch(d){c.handleError(d,"houdini.marketplace.updateLocation",a.failCallback)}},updateStores:function(a){try{a=a||{},b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.marketplace.updateStores",a),e.marketplace.updateStores(a)}catch(d){c.handleError(d,"houdini.marketplace.updateStores",a.failCallback)}}}}});"use strict";f.when("mash-util","mash-houdini-impl","mash-error-util").register("mash-houdini-transition",
function(b,e,c){return{transition:{boxedTopConsume:function(a){try{a=a||{},b.validateParameters1_3(a,["color","sourceRect","boxHeight","duration","url"]),b.validateParameters1_3(a.sourceRect,["left","top","width","height"]),b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.transition.boxedTopConsume",a),e.transition.boxedTopConsume(a)}catch(d){c.handleError(d,"houdini.transition.boxedTopConsume",a.failCallback)}}}}});"use strict";f.when("mash-util",
"mash-houdini-impl","mash-error-util").register("mash-houdini-pickuptracking",function(b,e,c){return{pickupTracking:{getTrackingEligibility:function(a){try{a=a||{},b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.pickupTracking.getTrackingEligibility",a),e.pickupTracking.getTrackingEligibility(a)}catch(d){c.handleError(d,"houdini.pickupTracking.getTrackingEligibility",a.failCallback)}},checkTrackingPermissions:function(a){try{a=a||{},b.validateFunctions1_3(a,
["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.pickupTracking.checkTrackingPermissions",a),e.pickupTracking.checkTrackingPermissions(a)}catch(d){c.handleError(d,"houdini.pickupTracking.checkTrackingPermissions",a.failCallback)}},requestTrackingPermissions:function(a){try{a=a||{},b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.pickupTracking.requestTrackingPermissions",a),e.pickupTracking.requestTrackingPermissions(a)}catch(d){c.handleError(d,
"houdini.pickupTracking.requestTrackingPermissions",a.failCallback)}},getTrackingSession:function(a){try{a=a||{},b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.pickupTracking.getTrackingSession",a),e.pickupTracking.getTrackingSession(a)}catch(d){c.handleError(d,"houdini.pickupTracking.getTrackingSession",a.failCallback)}},startTrackingSession:function(a){try{a=a||{},b.validateParameters1_3(a,["purchaseToken","purchaseId"]),b.validateFunctions1_3(a,
["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.pickupTracking.startTrackingSession",a),e.pickupTracking.startTrackingSession(a)}catch(d){c.handleError(d,"houdini.pickupTracking.startTrackingSession",a.failCallback)}},endTrackingSession:function(a){try{a=a||{},b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.pickupTracking.endTrackingSession",a),e.pickupTracking.endTrackingSession(a)}catch(d){c.handleError(d,"houdini.pickupTracking.endTrackingSession",
a.failCallback)}}}}});"use strict";f.when("mash-util","mash-houdini-impl","mash-error-util").register("mash-houdini-pfenotifications",function(b,e,c){return{pfeNotifications:{getSubscriptions:function(a){try{a=a||{},b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.pfeNotifications.getSubscriptions",a),e.pfeNotifications.getSubscriptions(a)}catch(d){c.handleError(d,"houdini.pfeNotifications.getSubscriptions",a.failCallback)}},setSubscriptions:function(a){try{a=
a||{},b.validateParameters1_3(a,["subscriptions"]),b.validateFunctions1_3(a,["successCallback","failCallback"]),a=c.wrapSuccessAndFailCallbacks("houdini.pfeNotifications.setSubscriptions",a),e.pfeNotifications.setSubscriptions(a)}catch(d){c.handleError(d,"houdini.pfeNotifications.setSubscriptions",a.failCallback)}}}}})});
/* ******** */
(function(c){var e=window.AmazonUIPageJS||window.P,g=e._namespace||e.attributeErrors,b=g?g("HoudiniMASH_AUI",""):e;b.guardFatal?b.guardFatal(c)(b,window):b.execute(function(){c(b,window)})})(function(c,e,g){c.when("mash-util","mash-houdini-impl","mash-error-util").register("mash-houdini-mshop-adapter-interface",function(b,c,d){return{cart:{didUpdate:function(a){try{a=a||{},b.validateParameters1_3(a,["newCartQuantity"]),b.validateFunctions1_3(a,["successCallback","failCallback"]),a=d.wrapSuccessAndFailCallbacks("cart.didUpdate",
a),c.cart.didUpdate(a)}catch(f){d.handleError(f,"cart.didUpdate",a.failCallback)}}},showAlert:function(a){try{a=a||{},b.validateParameters(a,["message","buttonTitles","successCallback"]),b.validateFunctions(a,["successCallback","failCallback"]),a=d.wrapSuccessAndFailCallbacks("showAlert",a),c.showAlert(a)}catch(f){d.handleError(f,"showAlert",a.failCallback)}},showImageGallery:function(a){try{a=a||{},b.validateParameters(a,["title","imageUrls"]),b.validateFunctions(a,["successCallback","failCallback"]),
a=d.wrapSuccessAndFailCallbacks("showImageGallery",a),c.showImageGallery(a)}catch(f){d.handleError(f,"showImageGallery",a.failCallback)}}}});c.when("mash-plugins").execute(function(b){try{c.register("mash-will-load",function(){return null})}catch(e){}b=b.slice();b.unshift("mash-interface-combiner");c.when.apply(c,b).register("mash-interface",function(){var b=Array.prototype.slice.call(arguments),c=b.shift();return c.apply(c,b)});return b});c.register("mash-plugins",function(){return["mash-core-interface",
"mash-signinout-interface","mash-houdini-interface","mash-houdini-mshop-adapter-interface"]})});
/* ******** */
